services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-prospects}"
    image: localstack/localstack
    ports:
      # - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG:-0}
      - AWS_ACCESS_KEY_ID=access_key_id
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=secret
    volumes:
      - "/root/.aws"
      - "./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
