name: Trigger auto deployment for prospectoutreachbackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/prospectoutreachbackend-AutoDeployTrigger-9279db9a-7ecc-44d2-b581-5ff4bafad14b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: prospectoutreachbackendacr.azurecr.io
          registryUsername: ${{ secrets.PROSPECTAICONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PROSPECTAICONTAINER_REGISTRY_PASSWORD }}
          containerAppName: prospectoutreachbackend
          resourceGroup: prospect-outreach
          imageToBuild: prospectoutreachbackendacr.azurecr.io/prospectoutreachbackend:${{ github.sha }}
          buildArguments: |
            buildArgumentsValues


